### ISSUE TITLE
Can't access Administration Console page with keycloak behind Kong Ingress Controller

### ISSUE THREAD

**Issue by jhonyscamacho** [codecentric/helm-charts#17]
**Is this a BUG REPORT or a FEATURE REQUEST?:** Bug Report

**Version of Helm and Kubectl:** 

- Helm v2.13.1 
- kubectl: 
  ```bash
  Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"} 
  Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Which chart**: codecentric/keycloak 4.11.1

**What happened:**

I have Keycloak behind [Kong Ingress Controller](https://github.com/Kong/kubernetes-ingress-controller). 
I 'm able to see keycloak welcome page at my **{url}/auth/**. However, when I click at **Administration Console** I am redirected to **{url}:8000/auth/admin/master/console/**

**What you expected to happen:**

When I click at **Administration Console** I should be redirect to **{url}/auth/admin/master/console/**

**How to reproduce it** (as minimally and precisely as possible):

1. Create a kubernetes cluster with kops in AWS
2. Installing [Kong Ingress Controller](https://github.com/Kong/kubernetes-ingress-controller) executing the following command:

```bash
helm install --name kong-develop --namespace develop stable/kong \
--set ingressController.enabled=true
```
3. Create an AWS Classic Load Balancer following the instructions bellow:

3.1 Basic Configuration

* **Load Balancer name**: KongDevelopLB
* **Create LB Inside**: Choose your cluster VPC

3.2 Listeners

| Load Balancer Protocol | Load Balancer Port | Instance Protocol | Instance Port |
|:----------------------:|:------------------:|:-----------------:|---------------|
| TCP | 80 | TCP | kong-proxy NodePort service |
| TCP | 443 | TCP | kong-proxy TLS NodePort service |
| TCP | 8444 | TCP | kong-admin NodePort service |

To help you detect the correct ports, take a look at the example image bellow:

![kong-services](https://user-images.githubusercontent.com/27226470/57199709-6ee7c900-6f58-11e9-9141-412d28d9f7dd.png)

In the example cluster shown in the image above:

* Load Balancer port **80** should point to instance port **32518**;
* Load Balancer port **443** should point to instance port **31021**;
* Load Balancer port **8444** should point to instance port **31725**.

3.3 Select Subnets

* **Select Subnets**: Select the cluster available subnets

3.4 Security Group

* **Assign a security group**: Create a new security group
* **Security group name**: KongDevelopLB-SecurityGroup

Type | Protocol | Port Range | Source
-- | -- | -- | --
Custom TCP Rule | TCP | 80 | Anywhere
Custom TCP Rule | TCP | 443 | Anywhere
Custom TCP Rule | TCP | 8444 | Anywhere

3.5 Configure Health Check

Health Check should point to kong-admin NodePort service. To help you find the correct port take a look at the example image bellow.

Based on the image bellow health check should point to **31725** port.

![kong-services](https://user-images.githubusercontent.com/27226470/57199709-6ee7c900-6f58-11e9-9141-412d28d9f7dd.png)

3.6 Add EC2 Instances

Add only the **node instances**.

3.8 Bind Load Balancer and Cluster

Edit the node cluster **Inbound security group** adding the following rules:

| Type | Protocol | Port Range | Source | Description |
|:----:|:--------:|:----------:|:------:|:-----------:|
| Custom TCP Rule | TCP | kong-admin NodePort service | Custom - **the KongDevelopLB security group id** | kongDevelopLB |
| Custom TCP Rule | TCP | kong-proxy NodePort service | Custom - **the KongDevelopLB security group id** | kongDevelopLB |
| Custom TCP Rule | TCP | kong-proxy TLS NodePort service | Custom - **the KongDevelopLB security group id** | kongDevelopLB |

Example:

![kong-services](https://user-images.githubusercontent.com/27226470/57199709-6ee7c900-6f58-11e9-9141-412d28d9f7dd.png)

Based on the image above:

* kong-admin NodePort service is **31725**.
* kong-proxy NodePort service is **32518**.
* kong-proxy TLS NodePort service is **31021**.

3.9 Create an alias to the Load Balancer

In Route53 service, create an alias record set inside inside cluster hosted zone to point to kong Load Balancer.

Example:

If your cluster DNS name is **kubernetes.mydomain.com**
you could create an alias record set like this: **develop.kubernetes.mydomain.com**

4. Installing keycloak behind Kong Ingress

4.1 Create a values.yaml file with the content bellow:

```yaml
init:
 image:
  pullPolicy: Always

keycloak:
 username: admin
 password: admin
 readinessProbe:
  timeoutSeconds: 60
 service:
  type: NodePort
 persistence:
  deployPostgres: true
  dbVendor: postgres
 ingress:
  enabled: true
  hosts:
   - develop.kubernetes.mydomain.com
 extraEnv: |
   - name: PROXY_ADDRESS_FORWARDING
     value: "true"
```
4.2 Install keycloak using the values.yaml files craeted in step 4.1

Execute the code bellow:

```bash
helm install --name keycloak-develop --namespace develop codecentric/keycloak --values values.yaml
```

4.3 Access keycloak 

Open the browser and access the following url: **http://develop.kubernetes.mydomain.com/** and you gonna be redirected to http://develop.kubernetes.mydomain.com/auth/

4.4 Access the Administration Console

Click at the Administration Console link and you will be redirected to **https://develop.kubernetes.mydomain.com:8443/auth/admin/master/console/**

**Further informations**:

When I install keycloak (with helm) on minikube exposing the the service as a NodePort service **without using ingress and load balancer** I'm able to access Administration Console page.

**Comment by jhonyscamacho** [comment]
Anyone?
Please guys, help me. I'm stuck in this problem and I have no idea how to solve it.

**Comment by jhonyscamacho** [comment]
Anybody?

**Comment by Igor-lkm** [comment]
I have similar issue here: https://github.com/helm/charts/issues/12272

TL;TR 

Keycloak works ok behind, for example, [ express-gateway](https://github.com/helm/charts/issues/12272#issuecomment-486097543). So, seems that the problem is with Kong then? 🤔

**Comment by jhonyscamacho** [comment]
In a [kong community in Gitter](https://gitter.im/Kong/kong) a received a tip: Configure reverse proxy (kong Ingress in this case) to properly set X-Forwarded-For and X-Forwarded-Proto HTTP headers. See [keycloak load balancer docs](https://www.keycloak.org/docs/1.9/server_installation_guide/topics/clustering/load-balancer.html)

I found [Response Transformer kong plugin](https://docs.konghq.com/hub/kong-inc/response-transformer/#enabling-the-plugin-on-a-service) that allows to add headers to the responses.

My question is: once I set the X-Forwarded-For and X-Forwarded-Proto headers in the response what kind of values should I configure in each header assuming that this values could be dynamic? Is there any environment variables that we could use?

**Comment by jhonyscamacho** [comment]
Just for the record: @bungle clarified my previous question.

According to @bungle kong sets the forwarded headers.

He shared with us this links:

https://github.com/Kong/kong/blob/master/kong/templates/nginx_kong.lua#L143-L146
https://github.com/Kong/kong/blob/master/kong/runloop/handler.lua#L869-L880

**Comment by method350** [comment]
Had a similar issue with kong. Get rid of kong, use [traefik](https://traefik.io) instead of this thing.

The trick was the proper combination of keycloak ingress and kong configuration.

Below my working the kong configuration

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: keycloak-ingress-conf
upstream:
  hash_on: cookie
  hash_on_cookie: X-KONG-STICKY
  hash_fallback: none
proxy:
  protocol: http
  path: /
  connect_timeout: 10000
  retries: 10
  read_timeout: 10000
  write_timeout: 10000
route:
  methods:
    - POST
    - GET
    - PATCH
    - HEAD
    - PUT
    - CONNECT
    - OPTIONS
    - DELETE
  regex_priority: 0
  strip_path: false
  preserve_host: true
  protocols:
    - http
    - https
```

Then configure the keycloak ingress with that kong config and you should be fine.

```
keycloak:
  replicas: 3
  ingress:
    annotations:
      kubernetes.io/ingress.class: kong
      configuration.konghq.com: "keycloak-ingress-conf"
```

**Comment by jhonyscamacho** [comment]
Hi guys!

The problem was solved.

The solution can be found [here](https://github.com/Kong/kubernetes-ingress-controller/issues/291).

@Igor-lkm take a look at the link above. Maybe it can help you.

**Comment by spacejam101** [comment]
@jhonyscamacho  Having the same issue also ^ but I binded the port on 80 with keycloak already and still having the error.

**Comment by Igor-lkm** [comment]
Update: https://github.com/Kong/kubernetes-ingress-controller/issues/291#issuecomment-540017080

**Comment by anand188** [comment]
does any one has any solution . Its not working with all suggested solutions
